# Config file for automatic testing at travis-ci.org

language: python

branches:
  only:
    - master

sudo: false

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35-django-22
    - python: 3.6
      env: TOXENV=py36-django-22
    - python: 3.7
      env: TOXENV=py37-django-22

    - python: 3.5
      env: TOXENV=py35-django-21
    - python: 3.6
      env: TOXENV=py36-django-21
    - python: 3.7
      env: TOXENV=py37-django-21

    - python: 3.4
      env: TOXENV=py34-django-20
    - python: 3.5
      env: TOXENV=py35-django-20
    - python: 3.6
      env: TOXENV=py36-django-20
    - python: 3.7
      env: TOXENV=py37-django-20

    - python: 3.4
      env: TOXENV=py34-django-111
    - python: 3.5
      env: TOXENV=py35-django-111
    - python: 3.6
      env: TOXENV=py36-django-111
    - python: 3.7
      env: TOXENV=py37-django-111

install: pip install -r requirements_test.txt

script: tox

after_success:
  - codecov
