# Config file for automatic testing at travis-ci.org

language: python

python: ["3.4", "3.5", "3.6", "3.7", "3.8"]

sudo: false

install: pip install -r requirements_test.txt

script: tox

after_success:
  - codecov
